version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /home/jk/projects/qa_server/mongo/db:/data/db
    restart: unless-stopped
    networks:
      mongo_net100:
        ipv4_address: 172.100.0.2
    command: mongod --bind_ip 127.0.0.1,172.100.0.2 --port 27018
    ports:
      - "27018:27018"  # Map the container's port to the host

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    networks:
      mongo_net100:
        ipv4_address: 172.100.0.3
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://172.100.0.2:27018/

networks:
  mongo_net100:
    driver: bridge
    ipam:
      config:
      - subnet: 172.100.0.0/16
        gateway: 172.100.0.1